version: '3.7'

services:
  service1:
    build:
      context: .
      dockerfile: apps/monorepo-app/Dockerfile
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: production

  service2:
    build:
      context: .
      dockerfile: apps/my-app/Dockerfile
    ports:
      - '3002:3000'
    environment:
      NODE_ENV: production
